// Generated by gencpp from file yolov5_findball/Silos.msg
// DO NOT EDIT!


#ifndef YOLOV5_FINDBALL_MESSAGE_SILOS_H
#define YOLOV5_FINDBALL_MESSAGE_SILOS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace yolov5_findball
{
template <class ContainerAllocator>
struct Silos_
{
  typedef Silos_<ContainerAllocator> Type;

  Silos_()
    : Silos_data()  {
    }
  Silos_(const ContainerAllocator& _alloc)
    : Silos_data(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _Silos_data_type;
  _Silos_data_type Silos_data;





  typedef boost::shared_ptr< ::yolov5_findball::Silos_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::yolov5_findball::Silos_<ContainerAllocator> const> ConstPtr;

}; // struct Silos_

typedef ::yolov5_findball::Silos_<std::allocator<void> > Silos;

typedef boost::shared_ptr< ::yolov5_findball::Silos > SilosPtr;
typedef boost::shared_ptr< ::yolov5_findball::Silos const> SilosConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::yolov5_findball::Silos_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::yolov5_findball::Silos_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::yolov5_findball::Silos_<ContainerAllocator1> & lhs, const ::yolov5_findball::Silos_<ContainerAllocator2> & rhs)
{
  return lhs.Silos_data == rhs.Silos_data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::yolov5_findball::Silos_<ContainerAllocator1> & lhs, const ::yolov5_findball::Silos_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace yolov5_findball

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::yolov5_findball::Silos_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::yolov5_findball::Silos_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yolov5_findball::Silos_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yolov5_findball::Silos_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yolov5_findball::Silos_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yolov5_findball::Silos_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::yolov5_findball::Silos_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5bb2bb79514f42a3bb9afaa460ea3556";
  }

  static const char* value(const ::yolov5_findball::Silos_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5bb2bb79514f42a3ULL;
  static const uint64_t static_value2 = 0xbb9afaa460ea3556ULL;
};

template<class ContainerAllocator>
struct DataType< ::yolov5_findball::Silos_<ContainerAllocator> >
{
  static const char* value()
  {
    return "yolov5_findball/Silos";
  }

  static const char* value(const ::yolov5_findball::Silos_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::yolov5_findball::Silos_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string Silos_data\n"
;
  }

  static const char* value(const ::yolov5_findball::Silos_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::yolov5_findball::Silos_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Silos_data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Silos_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::yolov5_findball::Silos_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::yolov5_findball::Silos_<ContainerAllocator>& v)
  {
    s << indent << "Silos_data: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.Silos_data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // YOLOV5_FINDBALL_MESSAGE_SILOS_H
