// Generated by gencpp from file yolov5_findball_msgs/Silos.msg
// DO NOT EDIT!


#ifndef YOLOV5_FINDBALL_MSGS_MESSAGE_SILOS_H
#define YOLOV5_FINDBALL_MSGS_MESSAGE_SILOS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace yolov5_findball_msgs
{
template <class ContainerAllocator>
struct Silos_
{
  typedef Silos_<ContainerAllocator> Type;

  Silos_()
    : x(0.0)
    , y(0.0)  {
    }
  Silos_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)  {
  (void)_alloc;
    }



   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;





  typedef boost::shared_ptr< ::yolov5_findball_msgs::Silos_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::yolov5_findball_msgs::Silos_<ContainerAllocator> const> ConstPtr;

}; // struct Silos_

typedef ::yolov5_findball_msgs::Silos_<std::allocator<void> > Silos;

typedef boost::shared_ptr< ::yolov5_findball_msgs::Silos > SilosPtr;
typedef boost::shared_ptr< ::yolov5_findball_msgs::Silos const> SilosConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::yolov5_findball_msgs::Silos_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::yolov5_findball_msgs::Silos_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::yolov5_findball_msgs::Silos_<ContainerAllocator1> & lhs, const ::yolov5_findball_msgs::Silos_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::yolov5_findball_msgs::Silos_<ContainerAllocator1> & lhs, const ::yolov5_findball_msgs::Silos_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace yolov5_findball_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::yolov5_findball_msgs::Silos_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::yolov5_findball_msgs::Silos_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yolov5_findball_msgs::Silos_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yolov5_findball_msgs::Silos_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yolov5_findball_msgs::Silos_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yolov5_findball_msgs::Silos_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::yolov5_findball_msgs::Silos_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ff8d7d66dd3e4b731ef14a45d38888b6";
  }

  static const char* value(const ::yolov5_findball_msgs::Silos_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xff8d7d66dd3e4b73ULL;
  static const uint64_t static_value2 = 0x1ef14a45d38888b6ULL;
};

template<class ContainerAllocator>
struct DataType< ::yolov5_findball_msgs::Silos_<ContainerAllocator> >
{
  static const char* value()
  {
    return "yolov5_findball_msgs/Silos";
  }

  static const char* value(const ::yolov5_findball_msgs::Silos_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::yolov5_findball_msgs::Silos_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 x\n"
"float32 y\n"
;
  }

  static const char* value(const ::yolov5_findball_msgs::Silos_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::yolov5_findball_msgs::Silos_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Silos_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::yolov5_findball_msgs::Silos_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::yolov5_findball_msgs::Silos_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // YOLOV5_FINDBALL_MSGS_MESSAGE_SILOS_H
